### ISSUE TITLE
Don't use lib64 directory

### ISSUE THREAD

**Issue by a-mair** [timeraider4u/libreoffice-online#1]
Hi,

could you please replace references to "/usr/lib64/" by "/usr/lib/" in libreoffice-online-*.ebuild, loolwsd.xml and loolwsd-copy-lo.xml?
They don't exist on 32bit systems.

Best regards,
Andreas

**Comment by timeraider4u** [comment]
Thanks for reporting this issue!

I have recently tested the replacement of /usr/lib64 with /usr/lib (see the lib64-branch of this repository), but this will result in failures with the libreoffice-online service (it will not find the requested document inside its chroot-environment) - seems that loolwsd in version 1.9 can not deal with symlinks properly. I will do some further investigation and try other fixes when I have more time.

**Comment by timeraider4u** [comment]
Dear @a-mair, 
can you try again if it now works with the latest commit?

By the way, out of curiosity, which system are you trying to run libreoffice-online on that is a 32-bit one?

**Comment by a-mair** [comment]
Hi @timeraider4u,

yes, it works. Thanks for changing that.

The system that I'm running libreoffice-online on is a virtual machine which runs a 32bit Gentoo. Once I find the time I will move to 64bit, but at the moment the box simply works for me.

**Comment by timeraider4u** [comment]
You are welcome! I will close this issue then.
